### PR TITLE
Coin Data Parsing

### PR DESCRIPTION
**Pull request by trevorm4**
Added script for coin parsing that can easily be run in the future with a new dataset. Also uploaded graphs for the nov-15 file

### CODE REVIEW

**Comment by andrewipark** [comment]
External Python package requirements for your script appear to be `seaborn` (implicitly `matplotlib`), and `pandas`. Is this information correct?

Graphs can go here for now, although we should really look into better long-term storage options for things that are strictly speaking, derived data.

**Comment by trevorm4** [comment]
Yeah, forgot about that, Ill add a virtualenv and make a new pull req.

**Comment by ianklatzco** [comment]
`we should really look into better long-term storage options for things that are strictly speaking, derived data.` Eh, maybe long-term. For now, it's probably worth the convenience of having derived data easily-grokkable, especially considering we're educationally-focused and newcomers would be more likely to get into it if they could easily see the graphs ahead of time.

Thank you for this, Trevor.

**Comment by ianklatzco** [comment]
(fwiw you can just push another commit and it'll add to this PR)

**Comment by ianklatzco** [comment]
@trevorm4 reminder

**Pull request merged**
